name: Check

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}-check
  cancel-in-progress: true

env:
  EXPORT: 1
  UNOPTIMIZED: 1

jobs:
  lint:
    name: Code quality
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v4
      - name: Setup latest NodeJS
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - name: Install project
        working-directory: ./website
        run: |
          npm install
      - name: Run lint
        working-directory: ./website
        run: |
          npm run lint

  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v4
      - name: Setup latest NodeJS
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - name: Install project
        working-directory: ./website
        run: |
          npm install
      - name: Test build
        working-directory: ./website
        run: |
          npm run build
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: exported-build
          path: ./website/out
